service: tesseract-ocr-example-py38
frameworkVersion: ">=3.0.0"

plugins:
    - serverless-python-requirements

provider:
  name: aws
  region: eu-north-1
  timeout: 90 # optional, in seconds, default is 6

custom:
  pythonRequirements:
    dockerizePip: true
    dockerFile: Dockerfile
    zip: true


layers:
  tesseractAl2:
    # specify path to layer content
    path: ../../ready-to-use/amazonlinux-2
    compatibleRuntimes:
      - python3.8

functions:
  tesseract-ocr:
    handler: main.lambda_handler
    runtime: python3.8
    layers:
      - { Ref: TesseractAl2LambdaLayer }
    events:
      - http:
          path: ocr
          method: post
          cors: true